/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hatsystem;

import data.Fabric;
import data.SqlQuery;
import data.Validation;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Friday
 */
public class EditCustomHatFromOrder extends javax.swing.JFrame {

    String hatID;
    /**
     * Creates new form EditHatFromOrder
     */
    public EditCustomHatFromOrder(String hatID) {
        initComponents();
        this.hatID = hatID;
        fillFabricComboBox();
        fillValues();
        lblErrorMessage.setVisible(false);
    }
    
    private void editHat(){
        if (hatID.substring(1, 2).equalsIgnoreCase("C")){
            
        }
    }
    
    private void fillValues(){
        String chosenHatID = hatID.substring(1, 9).trim();
        HashMap<String, String> hatHM = SqlQuery.getRow("SELECT * FROM hat Where Hat_ID = "+ chosenHatID +";");
        tfHatName.setText(hatHM.get("Name"));
        tfPrice.setText(hatHM.get("Price"));
        cmbSize.setSelectedItem(hatHM.get("Size"));
        
        if(hatHM.get("Finished").equals("1")){
            cboxDone.setSelected(true);
        }
        else{
            cboxDone.setSelected(false);
        }
        
        if(hatHM.get("Worker").equals("1")){
            cmbWorker.setSelectedItem("Otto");
        }
        else{
            cmbWorker.setSelectedItem("Judith");
        }
        
        taDescription.setText(hatHM.get("Description"));
        
        HashMap<String, String> hatFabric = Fabric.getFabricFromID(hatHM.get("Hat_Fabric"));
        cmbFabricName.setSelectedItem(hatFabric.get("Name"));
        fillColorComboBox(hatFabric.get("Name"));
        String color = hatFabric.get("Color");
        cmbColor.setSelectedItem(color);
    }
    
        /**
     * Fills the fabric combo box with fabric options.
     */
    private void fillFabricComboBox() {

        HashSet<String> fabrics = Fabric.getAllFabricNames();

        for (String s : fabrics) {
            cmbFabricName.addItem(s);
        }
    }

    private void fillColorComboBox(String fabricName) {

        cmbColor.removeAllItems();

        ArrayList<String> colors = Fabric.getFabricColors(fabricName);

        for (String s : colors) {
            cmbColor.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSize = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbFabricName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        cboxDone = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lblHatName = new javax.swing.JLabel();
        tfHatName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbWorker = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        lblCheckName = new javax.swing.JLabel();
        lblCheckPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Storlek");

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXS", "XS", "S", "M", "L", "XL", "XXL" }));
        cmbSize.setSelectedIndex(3);

        jLabel2.setText("Tygnamn");

        cmbFabricName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFabricNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Färg");

        jLabel4.setText("Pris");

        cboxDone.setText("Ja");

        jLabel5.setText("Färdigsydd");

        lblHatName.setText("Hattnamn");

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane1.setViewportView(taDescription);

        jLabel6.setText("Beskrivning");

        btnSave.setText("Spara ändringar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("Hattmakare");

        cmbWorker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Otto", "Judith" }));

        jLabel8.setText("Redigera hatt");

        lblErrorMessage.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMessage.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHatName)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel7))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxDone)
                            .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHatName)
                            .addComponent(tfPrice)
                            .addComponent(cmbFabricName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCheckName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCheckPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(261, 261, 261))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHatName)
                    .addComponent(tfHatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbFabricName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboxDone)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessage)
                .addGap(19, 19, 19)
                .addComponent(btnSave)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFabricNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFabricNameActionPerformed
    
        String chosenFabric = cmbFabricName.getSelectedItem().toString();

        fillColorComboBox(chosenFabric);
    }//GEN-LAST:event_cmbFabricNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      saveChanges();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveChanges(){
        lblErrorMessage.setVisible(false);
        String chosenHatID = hatID.substring(1, 9).trim();
        HashMap<String, String> hatHM = SqlQuery.getRow("SELECT * FROM hat Where Hat_ID = "+ chosenHatID +";");
        
        String hatName = tfHatName.getText();
        String hatPrice = tfPrice.getText();
        String fabricName = cmbFabricName.getSelectedItem().toString();
        String fabricColor = cmbColor.getSelectedItem().toString();
        String hatSize = cmbSize.getSelectedItem().toString();
        boolean hatDone = cboxDone.isSelected();
        String hatMaker = cmbWorker.getSelectedItem().toString();
        String description = taDescription.getText();
        
        String isFinished = "1";
        String worker = "1";
        
        if(!hatDone){
            isFinished = "0";
        }
        
        if (hatMaker.equals("Judith")) {
            worker = "2";
        }
        
        if (hatName.isBlank() || hatPrice.isBlank()){
            lblErrorMessage.setText("Vänligen se till att hattnamn och pris är ifyllt");
            lblErrorMessage.setVisible(true);
        }
        else if (!Validation.isDouble(hatPrice)){
            lblErrorMessage.setText("Priset får bara innehålla siffror");
            lblErrorMessage.setVisible(true);
        }
        else{
            if(!hatHM.get("Name").equals(hatName)){
             SqlQuery.update("UPDATE hat SET Name = '"+ hatName +"' WHERE Hat_ID = "+ chosenHatID +";");
            }
            if (!hatHM.get("Price").equals(hatPrice)){
              SqlQuery.update("UPDATE hat SET Price = "+ hatPrice +" WHERE Hat_ID = "+ chosenHatID +";");
            }
            if (!hatHM.get("Size").equals(hatSize)) {
               SqlQuery.update("UPDATE hat SET Size = '"+ hatSize +"' WHERE Hat_ID = "+ chosenHatID +";");
            }
            if (!hatHM.get("Finished").equals(isFinished)) {
               SqlQuery.update("UPDATE hat SET Finished = "+ isFinished +" WHERE Hat_ID = "+ chosenHatID +";");
            }
            if (!hatHM.get("Worker").equals(worker)) {
                SqlQuery.update("UPDATE hat SET Worker = "+ worker +" WHERE Hat_ID = "+ chosenHatID +";");
            }
            if (!hatHM.get("Description").equals(description)) {
                SqlQuery.update("UPDATE hat SET Description = '"+ description +"' WHERE Hat_ID = "+ chosenHatID +";");
            }
            int fabricID = Fabric.getFabricID(fabricName, fabricColor);
            if (!hatHM.get("Hat_Fabric").equals(fabricID)) {
                SqlQuery.update("UPDATE hat SET Hat_Fabric = "+ fabricID +" WHERE Hat_ID = "+ chosenHatID +";");
            }
            JOptionPane.showMessageDialog(null, "Ändringar sparade");
            fillValues();
            
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cboxDone;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbFabricName;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JComboBox<String> cmbWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckName;
    private javax.swing.JLabel lblCheckPrice;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblHatName;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField tfHatName;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
